### ISSUE TITLE
KeyError because font 'Roman' is not known

### ISSUE THREAD

**Issue by sawcordwell** [brandon-rhodes/python-bookbinding#5]
I am not sure what the reason is, perhaps because of different systems or because reportlab has changed, but I get a KeyError because of `canvas.setFont('Roman', FONT_SIZE)` at document.py [line 26](https://github.com/brandon-rhodes/python-bookbinding/blob/5e65c6/bookbinding/document.py#L26) and [line 65](https://github.com/brandon-rhodes/python-bookbinding/blob/5e65c6/bookbinding/document.py#L65) however `canvas.setFont('Times-Roman', FONT_SIZE)` works for me. Perhaps there should be some way to easily set the font from the API, or a way to detect which fonts are installed?

I am happy to work on this if it is something that would be useful.

**Comment by brandon-rhodes** [comment]
I like the idea that the font should be configurable, but it will be a few weeks before I can look at the code in any detail. Thanks for the idea, and I'll keep this issue open until I can address it!

**Comment by brandon-rhodes** [comment]
Thanks for the pull request! This is now a feature. Let me know if you have any further problems!
